### PR TITLE
Update EventMessage to contain `userId` when source is group or room.

### PR DESCRIPTION
**Pull request by tenniscp25**

### CODE REVIEW

**Comment by moleike** [comment]
@tenniscp25 thanks for your patch!
For reference this is explained here: https://developers.line.biz/en/reference/messaging-api/#common-properties

**Comment by moleike** [comment]
I will try to make a release soon, hopefully tonight

**Comment by tenniscp25** [comment]
Thanks!

**Comment by moleike** [comment]
@tenniscp25 just released 0.7.1 in case you want to upgrade, thanks.

**Pull request merged**
